### PR TITLE
Replace badge object -> assertion

### PR DESCRIPTION
**Pull request by davidlj95**
Revocation list property `revokedAssertions` should contain id for assertions, not for badges

### CODE REVIEW

**Comment by ottonomy** [comment]
👍 that is a good clarification. "Badge" is an overloaded term that sometimes refers to an Assertion and sometimes to a BadgeClass.

**Comment by davidlj95** [comment]
Exactly @ottonomy, that's why in our office we've stopped talking about badges when we mean assertions

**Comment by jbohrer** [comment]
Thanks @davidlj95. I'll move this PR to the new Develop branch.

**Comment by davidlj95** [comment]
Found another "badge object" in `extensions/index.md`, replaced by "assertion"

**Comment by ottonomy** [comment]
"Badge object" was the correct term for your second commit bo84ddf. Assertions, Badge Classes, and Issuer Profiles may all be the subject of an Endorsement. I propose that we merge only the first commit.

**Comment by jbohrer** [comment]
Per workgroup call on 28 March, merge only https://github.com/IMSGlobal/openbadges-specification/pull/214/commits/364ab9c3f6a07b99bd16a4d4069f0ded785b83b1

**Comment by davidlj95** [comment]
@jbohrer @amiller-ims  reverted last commit. BTW how can we participate in these workgroup calls and in the workgroup in general? Thanks

**Comment by jbohrer** [comment]
@davidlj95 Anyone can contribute issues, comments, suggestions to the Open Badges specification here in the public repo as you did. IMS Global manages the specification, so final decisions are made by its members through its decision-making structure. The workgroup calls are available to IMS members ([further info](https://www.imsglobal.org/imsmembership.html)).

**Comment by davidlj95** [comment]
Perfect, thanks @jbohrer !

**Pull request closed without merging**
